CREATE DATABASE IF NOT EXISTS aram_db;
USE aram_db;

CREATE TABLE IF NOT EXISTS inventory (
  ShopID INT AUTO_INCREMENT PRIMARY KEY,
  ShopName VARCHAR(100) NOT NULL,
  District VARCHAR(100) NOT NULL,
  CurrentStock INT NOT NULL,
  MonthlyDemand INT NOT NULL,
  Population INT NOT NULL,
  LastMonthConsumption INT NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
